package main

import (
	"database/sql"
	"fmt"
	"log"
	"net/http"
	"time"

	_ "github.com/lib/pq"

	"multitrackticketing/config"
	_ "multitrackticketing/docs" // This will be generated by swag init
	"multitrackticketing/internal/client/sessionize"
	delivery "multitrackticketing/internal/delivery/http"
	"multitrackticketing/internal/repository/postgres"
	"multitrackticketing/internal/services"
)

// @title Multi-Track Ticketing API
// @version 1.0
// @description This is the backend API for a conference ticketing system.
// @host localhost:8080
// @BasePath /
func main() {
	// 1. Configuration
	cfg, err := config.Load()
	if err != nil {
		log.Fatalf("Failed to load config: %v", err)
	}

	// 2. Database Connection
	db, err := sql.Open("postgres", cfg.DBUrl)
	if err != nil {
		log.Fatal(err)
	}
	defer db.Close()

	if err := db.Ping(); err != nil {
		log.Fatal("Could not connect to database:", err)
	}
	fmt.Println("Connected to Database")

	// 3. Init Layers
	eventRepo := postgres.NewEventRepository(db)
	sessionRepo := postgres.NewSessionRepository(db)
	userRepo := postgres.NewUserRepository(db)
	roleRepo := postgres.NewRoleRepository(db)
	sessionizeFetcher := sessionize.NewHTTPFetcher(nil)
	manageScheduleService := services.NewManageScheduleService(eventRepo, sessionRepo, sessionizeFetcher, 10*time.Second)
	scheduleController := delivery.NewScheduleController(manageScheduleService)

	jwtSecret := cfg.JWTSecret
	if jwtSecret == "" {
		if cfg.Environment == "production" {
			log.Fatal("JWT_SECRET is required in production")
		}
		jwtSecret = "dev-secret-change-in-production"
	}
	authService := services.NewAuthService(userRepo, roleRepo, jwtSecret, cfg.JWTExpiry)
	authController := delivery.NewAuthController(authService)

	// 4. Router
	mux := delivery.NewRouter(scheduleController, authController)

	// 5. Server
	port := ":" + cfg.Port
	fmt.Printf("Server starting on %s\n", port)
	if err := http.ListenAndServe(port, mux); err != nil {
		log.Fatal(err)
	}
}
