@startuml Detailed Admin Create Event Flow
title Detailed Admin Flow for Creating an Event - Admin vs System Actions

|Admin|
start
:Accesses admin portal\n(authentication required);
:Navigates to dashboard;
:Clicks "Create New Event";
:Introduces Sessionize key;

|System|
:Loads event session and rooms from Sessionize API;
:Sets admin user as event creator and owner;
:Returns event information (Sessions and Rooms);

|Admin|
repeat
:Visualizes event information; 
note left
    Views session details and rooms fetched
end note
:Reviews imported data;
:Verifies session details\n(times, speakers, rooms);
:Assign Room Capacities;
:View Session Bookings and Occupancy on real time;
note left
    Updates occupancy 
end note


fork
  :Manages team members;
fork again
  :Remove team member flow;
fork again
  :End Event flow;
end fork
stop

@enduml
